### ISSUE TITLE
Update version in PyPi to 0.9.1

### ISSUE THREAD

**Issue by palfrey** [opacam/Cohen3#15]
https://pypi.org/project/Cohen3/ has 0.8.3 but the repo has 0.9.1

**Comment by opacam** [comment]
Yeah, I'm  aware of that, I will try to make a new `pypi` package as soon as possible.

@palfrey, !!Thanks to remind me this fact!! :+1:

**Comment by opacam** [comment]
Ok, I just published the `PyPI` packages as well as created a new release (also published in `PyPI`).

This new release was created because there was some issues that we had to address (#16 and #18).

I uploaded the missing `PyPI` packages for version `0.9.X` but I don't recommend to use that ones, except for the last one `0.9.2` (because of the mentioned issues above) :wink:

@palfrey , I close this issue because it has been addressed, **thanks again!**
